application:
  timeout:
    read: 1000
    write: 1000
  port: 8080
  host: "localhost"
  uploadPath: "./upload"
  mode: "debug"
  appId: "go"
  apiBaseRoute: "/api"
  sessionKey: "MTYzNDE5MDk1N3xEdi1CQkFFQ180SUFBUkFCRUFBQUhQLUNBQUVHYzNSeWFXNW5EQVlBQkdGMWRHZ0VZbTl2YkFJQ0FBRT18hwhK_84XTSejk0JNBo8olPV9CSGCreMQUlTx_b0aci4%3D"
  
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: 9955
  dbname: "demo"

redis:
  host: "127.0.0.1:6379"
  password: ""
  db: 0