application:
  port: 8080
  host: "bookShop"
  uploadPath: "./upload"
  mode: "dev"
  apiBaseRoute: "/api"
  cors:
    allowOrigins: ["http://bookShop:3000"]
  
databases:
  shopCart:
    host: "postgresql"
    port: 5432
    user: "test"
    password: "secret"
    dbname: "shop_cart"

  # default:
  #   host: "localhost"
  #   port: 5432
  #   user: "postgres"
  #   password: 9955
  #   dbname: "postgres"

redis:
  host: "redis:6379"
  password: ""
  db: 0