version: '3.8'

services:
  app:
    container_name: bookShop
    build: 
      context: .
    restart: always
    ports:
      - '8080:8080'
    networks:
      - bookShop
      - redis
      - postgresql

networks:
  bookShop:
    name: bookShop
    driver: bridge
  postgresql:
    name: postgresql
    external: true
  redis: 
    name: redis
    external: true