// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: c
func (_m *UserHandler) CreateUser(c *gin.Context) {
	_m.Called(c)
}

// DeleteUser provides a mock function with given fields: c
func (_m *UserHandler) DeleteUser(c *gin.Context) {
	_m.Called(c)
}

// GetUser provides a mock function with given fields: c
func (_m *UserHandler) GetUser(c *gin.Context) {
	_m.Called(c)
}

// GetUserList provides a mock function with given fields: c
func (_m *UserHandler) GetUserList(c *gin.Context) {
	_m.Called(c)
}

// ModifyUser provides a mock function with given fields: c
func (_m *UserHandler) ModifyUser(c *gin.Context) {
	_m.Called(c)
}

// UpdateUser provides a mock function with given fields: c
func (_m *UserHandler) UpdateUser(c *gin.Context) {
	_m.Called(c)
}
